services:
  postgres:
    image: postgres:17.5
    container_name: trip_planner-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trip_planner
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: