version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: trip-planner-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trip_planner
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: trip-planner-backend
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: trip_planner
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      DATABASE_SSL: false
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: trip-planner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
